from typing import (
    Any, Callable, Iterable, Tuple, List, TextIO, Sequence,
    Optional, overload, TypeVar, Pattern, Type
)

class error(Exception):...

def setupterm() -> None: ...
def tparm(arg: str, *args: int) -> None: ...
def tigetstr(arg: str) -> str: ...

# vim: syntax=python
