
class DBusException(Exception):
    def __init__(self, *args, **kwargs) -> None: ...

class MissingErrorHandlerException(DBusException):
    def __init__(self) -> None: ...

class MissingReplyHandlerException(DBusException):
    def __init__(self) -> None: ...

class ValidationException(DBusException):
    def __init__(self, msg: str='') -> None: ...

class IntrospectionParserException(DBusException):
    def __init__(self, msg: str='') -> None: ...

class UnknownMethodException(DBusException):
    def __init__(self, method: str) -> None: ...

class NameExistsException(DBusException):
    def __init__(self, name: str) -> None: ...